<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LLT.LibreHardwareMonitorLib" Version="1.0.2"/>
        <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.30"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Resources\"/>
        <Folder Include="database\"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\*.ico"/>
    </ItemGroup>

</Project>